### ISSUE TITLE
您好，我这解码只是单纯的把bundles内的dat文件复制到了bundles-decrypt内是怎么回事

### ISSUE THREAD

**Issue by Flolady** [66hh/1999decrypt#10]
![tmp54F4](https://github.com/66hh/1999decrypt/assets/60363224/04605925-ff0b-4bf1-afdf-3a1d4fcad741)
![tmp856C](https://github.com/66hh/1999decrypt/assets/60363224/19206557-8ef2-4bc4-a3e9-8e974ad24512)
就是点击cb3-decrypt.py后，只是单纯的复制了一遍。
![tmp1624](https://github.com/66hh/1999decrypt/assets/60363224/0f0940b9-eec4-414b-ba7f-6a6b41bc2060)

**Comment by 66hh** [comment]
不是单纯复制，decrypt文件夹里是解密好的，原本解密好的是dat-dec文件不过最近有人pr改了下改成了直接解密好就复制到decrypt文件夹里
