### ISSUE TITLE
where the character data is located

### ISSUE THREAD

**Issue by typetree** [66hh/1999decrypt#2]
The bundle has been successfully decrypted, and I am looking to find **where the character data is located**. 
And should I also use the CB3 decryption method for this?

**Comment by 66hh** [comment]
Excel？Excel has independent encryption and needs to obtain the AES key issued online for decryption

**Comment by 66hh** [comment]
These data headers are SHA1 certificates signed with RSA, and data segments are encrypted by AES

**Comment by 66hh** [comment]
AES keys and RSA public keys appear to be obtained online
