### ISSUE TITLE
第一次尝试解包dat文件，请问在运行了解密脚本后我应该怎么做？

### ISSUE THREAD

**Issue by LuoZe02151223** [66hh/1999decrypt#4]
在拆开base.apk后，我在\base\assets\Android\bundles下找到了大量的dat文件，随后我使用了您的解密程序cb3-decrypt.py，没有报错并且文件后缀被重新命名为dat-dex，下面一步要如何是好？我无法判断文件的具体类型，还请大佬指导！

**Comment by LuoZe02151223** [comment]
大佬，关于“角色live2d的moc3文件位于Assets\ZResourcesLib\live2d\roles\角色id_角色名字\角色id_角色名字”，我并没有在base文件夹中找到该目录，求帮助

**Comment by 66hh** [comment]
> 

丢进assetstudio里解包就行了

**Comment by 66hh** [comment]
> 大佬，关于“角色live2d的moc3文件位于Assets\ZResourcesLib\live2d\roles\角色id_角色名字\角色id_角色名字”，我并没有在base文件夹中找到该目录，求帮助

这个是unity ab包里的文件路径

**Comment by LuoZe02151223** [comment]
感谢

**Comment by LuoZe02151223** [comment]
已经成功了，旧版的accessstudio（0.13）没法读这些文件，升级以后就没有问题了。
还有，大佬找到文本的位置了吗？翻了一遍没找到

**Comment by devil-king-1999** [comment]
借楼，我这边使用CB3之后，生成dat-dec的文件，导入as里面，并不能到处有用的资源
和不使用cb3，导出的资源是一样，请问是我哪里操作错了么？

**Comment by LuoZe02151223** [comment]
> 
我这边是没问题的，有试过升级一下as的版本吗？

**Comment by devil-king-1999** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好， 我已经收到你的来件。我回尽快回复你的！

**Comment by LuoZe02151223** [comment]
> 借楼，我这边使用CB3之后，生成dat-dec的文件，导入as里面，并不能到处有用的资源 和不使用cb3，导出的资源是一样，请问是我哪里操作错了么？

我这边是没问题的，有试过升级一下as的版本吗？

**Comment by 66hh** [comment]
> 借楼，我这边使用CB3之后，生成dat-dec的文件，导入as里面，并不能到处有用的资源 和不使用cb3，导出的资源是一样，请问是我哪里操作错了么？

能发一下你解密前的文件吗，我看看什么问题

**Comment by 66hh** [comment]
> 已经成功了，旧版的accessstudio（0.13）没法读这些文件，升级以后就没有问题了。 还有，大佬找到文本的位置了吗？翻了一遍没找到

文本应该在数值表那边，是在线下发的一个aes秘钥解密的

**Comment by devil-king-1999** [comment]
> 

我是通过官网apk直接解压，拿里面bundle目录下面的文件；as使用的版本0.15.24

**Comment by 66hh** [comment]
> > 
> 
> 我是通过官网apk直接解压，拿里面bundle目录下面的文件；as使用的版本0.15.24

发下解密前和解密后的文件呢，你这光说我也不知道你这啥问题啊

**Comment by devil-king-1999** [comment]
> > > 
> > 
> > 
> > 我是通过官网apk直接解压，拿里面捆绑目录下面的文件;as使用的版本0.15.24
> 
> 发下解密前和解密后的文件呢，你这光说我也不知道你这啥问题啊

是我的操作问题，换了一个as，0.16的就完全可以读出来了；

**Comment by QIanyi-NK** [comment]
> > 已经成功了，旧版的accessstudio（0.13）没法读这些文件，升级以后就没有问题了。 还有，大佬找到文本的位置了吗？翻了一遍没找到
> 
> 文本应该在数值表那边，是在线下发的一个aes秘钥解密的
请问我可以获取到这个AES密钥吗？

**Comment by 66hh** [comment]
> > > 已经成功了，旧版的accessstudio（0.13）没法读这些文件，升级以后就没有问题了。 还有，大佬找到文本的位置了吗？翻了一遍没找到
> > 
> > 
> > 文本应该在数值表那边，是在线下发的一个aes秘钥解密的
> > 请问我可以获取到这个AES密钥吗？

在一个http请求里，你可以抓包找一下，会有一个rsa的公钥还有aes的秘钥和iv，先去掉头部的rsa数据然后用aes秘钥解密就完事了

**Comment by QIanyi-NK** [comment]
> > > > 已经成功了，旧版的accessstudio（0.13）没法读这些文件，升级以后就没有问题了。 还有，大佬找到文本的位置了吗？翻了一遍没找到
> > > 
> > > 
> > > 文本应该在数值表那边，是在线下发的一个aes秘钥解密的
> > > 请问我可以获取到这个AES密钥吗？
> 
> 在一个http请求里，你可以抓包找一下，会有一个rsa的公钥还有aes的秘钥和iv，先去掉头部的rsa数据然后用aes秘钥解密就完事了

大佬您好，刚刚试了一下。请问抓包之后返回的文件是加密的该怎么处理呢？

**Comment by 66hh** [comment]
> > > > > 已经成功了，旧版的accessstudio（0.13）没法读这些文件，升级以后就没有问题了。 还有，大佬找到文本的位置了吗？翻了一遍没找到
> > > > 
> > > > 
> > > > 文本应该在数值表那边，是在线下发的一个aes秘钥解密的
> > > > 请问我可以获取到这个AES密钥吗？
> > 
> > 
> > 在一个http请求里，你可以抓包找一下，会有一个rsa的公钥还有aes的秘钥和iv，先去掉头部的rsa数据然后用aes秘钥解密就完事了
> 
> 大佬您好，刚刚试了一下。请问抓包之后返回的文件是加密的该怎么处理呢？

之前我看好像是没加密的来着，记不得了，你自己逆向一下吧，这玩意得逆向才知道算法

**Comment by Higanoneko** [comment]
> > > > > > 已经成功了，旧版的accessstudio（0.13）没法读这些文件，升级以后就没有问题了。 还有，大佬找到文本的位置了吗？翻了一遍没找到
> > > > > 
> > > > > 
> > > > > 文本应该在数值表那边，是在线下发的一个aes秘钥解密的
> > > > > 请问我可以获取到这个AES密钥吗？
> > > 
> > > 
> > > 在一个http请求里，你可以抓包找一下，会有一个rsa的公钥还有aes的秘钥和iv，先去掉头部的rsa数据然后用aes秘钥解密就完事了
> > 
> > 
> > 大佬您好，刚刚试了一下。请问抓包之后返回的文件是加密的该怎么处理呢？
> 
> 之前我看好像是没加密的来着，记不得了，你自己逆向一下吧，这玩意得逆向才知道算法

可以询问一下关于RSA和AES相关的问题吗？
我这边是通过 HttpCanary 抓取到了一些数据：
[R1999-Catch.zip](https://github.com/66hh/1999decrypt/files/11779214/R1999-Catch.zip)
找了一下， 根据#5那边的一些东西抓取到了可以用Base64+Gunzip解码的内容，但是对于密钥的抓取没有特别大的头绪，还请不吝赐教。

**Comment by saltyplum** [comment]
> > > > > > > 已经成功了，旧版的accessstudio（0.13）没法读这些文件，升级以后就没有问题了。 还有，大佬找到文本的位置了吗？翻了一遍没找到
> > > > > > 
> > > > > > 
> > > > > > 文本应该在数值表那边，是在线下发的一个aes秘钥解密的
> > > > > > 请问我可以获取到这个AES密钥吗？
> > > > 
> > > > 
> > > > 在一个http请求里，你可以抓包找一下，会有一个rsa的公钥还有aes的秘钥和iv，先去掉头部的rsa数据然后用aes秘钥解密就完事了
> > > 
> > > 
> > > 大佬您好，刚刚试了一下。请问抓包之后返回的文件是加密的该怎么处理呢？
> > 
> > 
> > 之前我看好像是没加密的来着，记不得了，你自己逆向一下吧，这玩意得逆向才知道算法
> 
> 可以询问一下关于RSA和AES相关的问题吗？ 我这边是通过 HttpCanary 抓取到了一些数据： [R1999-Catch.zip](https://github.com/66hh/1999decrypt/files/11779214/R1999-Catch.zip) 找了一下， 根据#5那边的一些东西抓取到了可以用Base64+Gunzip解码的内容，但是对于密钥的抓取没有特别大的头绪，还请不吝赐教。

你好，我也卡在这一步了，想问一下有没有经验可以分享
