### ISSUE TITLE
moc3的还原

### ISSUE THREAD

**Issue by tndwelcome** [66hh/1999decrypt#6]
你好，可以请教下如何还原moc3数据吗，AssetStudio导出的L2D相关文件非常分散，看内容能明白各自的作用，但不知道如何将它们删减后组合成原始文件。
以前只接触过atlas，skel组合的形式，moc3则是完全抓瞎了，网上搜索到moc3的相关教程都是从零开始制作或是直接使用的

**Comment by 66hh** [comment]
这玩意moc3数据是写MonoBehaviour里的，你可以用assetstudio给MonoBehaviour的raw数据dump出来然后用winhex找到moc3文件头并删掉前面多余的字节然后搞个空白的模型文件给moc3文件和贴图替换进去就可以正常打开了

**Comment by tndwelcome** [comment]
修改文件头其他游戏里用过，moc3的配置已经用其他文件在Live2DViewerEX练习了，
但"用assetstudio给MonoBehaviour的raw数据dump出来"
就是这个不知道如何操作，以前都不知道assetstudio有这功能，可export下的dump和raw弄出来的都是同样的零散文件
用extract file出来的文件内倒是找到了MOC3的文件头，可把前面的全部删除后载入后直接显示模型读取失败。
用的是net6.v0.16.47的版本，尝试用关键词搜了一下，也没找到相关教程（悲），难道是命令行的方式吗。

**Comment by 66hh** [comment]
> 修改文件头其他游戏里用过，moc3的配置已经用其他文件在Live2DViewerEX练习了， 但"用assetstudio给MonoBehaviour的raw数据dump出来" 就是这个不知道如何操作，以前都不知道assetstudio有这功能，可export下的dump和raw弄出来的都是同样的零散文件 用extract file出来的文件内倒是找到了MOC3的文件头，可把前面的全部删除后载入后直接显示模型读取失败。 用的是net6.v0.16.47的版本，尝试用关键词搜了一下，也没找到相关教程（悲），难道是命令行的方式吗。

就是export raw，模型错误这个可能是moc3文件后面多了几个字节什么的，你用他们做的moc3的imhex模板看一下删掉后面多的字节就行了

**Comment by 66hh** [comment]
> 

是零散的俩文件贴图和moc3 这俩分别抽出来然后加上一个live2d的json文件就行了

**Comment by 66hh** [comment]
顺便一说imhex的moc3模板在之前的反舌鸟漏洞的仓库里有

**Comment by tndwelcome** [comment]
明白了！是我给理解偏了，以为MonoBehaviour的文件变成一个提取出来后，在用16位编辑器把moc3之外的删除，看到回答时突然反应了过来，意思实际是指moc3文件是里面的那堆的其中之一，大小排序，看一下文件名立刻就找到了，改完之后扔进Live2DViewerEX就运行了，蒸腾了好几周，脑子始终都没转过弯来，瘫

**Comment by tndwelcome** [comment]
谢谢

**Comment by WilliamDou11** [comment]
> 明白了！是我给理解偏了，以为MonoBehaviour的文件变成一个提取出来后，在用16位编辑器把moc3之外的删除，看到回答时突然反应了过来，意思实际是指moc3文件是里面的那堆的其中之一，大小排序，看一下文件名立刻就找到了，改完之后扔进Live2DViewerEX就运行了，蒸腾了好几周，脑子始终都没转过弯来，瘫

你好，方便请教一下您是如何得到model3.json文件的嘛？我得到了moc3文件和两个贴图文件，但是剩下的model3.json和其他表情json文件我无从下手……

**Comment by tndwelcome** [comment]
> > 明白了！是我给理解偏了，以为MonoBehaviour的文件变成一个提取出来后，在用16位编辑器把moc3之外的删除，看到回答时突然反应了过来，意思实际是指moc3文件是里面的那堆的其中之一，大小排序，看一下文件名立刻就找到了，改完之后扔进Live2DViewerEX就运行了，蒸腾了好几周，脑子始终都没转过弯来，瘫
> 
> 你好，方便请教一下您是如何得到model3.json文件的嘛？我得到了moc3文件和两个贴图文件，但是剩下的model3.json和其他表情json文件我无从下手……

model3.json要进EX工作室自己写，导入moc3后跟着流程创建就行，fade的动作文件可以用GFLMotionConverter转化成json，一部分数值会有错误看到动作不连贯要自己对照源文件改一下数值，exp3表情……忘记当初怎么弄的了，但看编辑时间应该没找到批量，按着解包的json文件自己一个个在ex工作室照着数调完保存的，反正就是三四个参数工作量也不大。
P.S.贴图文件有四个，两个黑的是发光特效

**Comment by WilliamDou11** [comment]
> > > 明白了！是我给理解偏了，以为MonoBehaviour的文件变成一个提取出来后，在用16位编辑器把moc3之外的删除，看到回答时突然反应了过来，意思实际是指moc3文件是里面的那堆的其中之一，大小排序，看一下文件名立刻就找到了，改完之后扔进Live2DViewerEX就运行了，蒸腾了好几周，脑子始终都没转过弯来，瘫
> > 
> > 你好，方便请教一下您是如何得到model3.json文件的嘛？我得到了moc3文件和两个贴图文件，但是剩下的model3.json和其他表情json文件我无从下手……
> 
> model3.json要进EX工作室自己写，导入moc3后跟着流程创建就行，fade的动作文件可以用GFLMotionConverter转化成json，一部分数值会有错误看到动作不连贯要自己对照源文件改一下数值，exp3表情……忘记当初怎么弄的了，但看编辑时间应该没找到批量，按着解包的json文件自己一个个在ex工作室照着数调完保存的，反正就是三四个参数工作量也不大。
> P.S.贴图文件有四个，两个黑的是发光特效

谢谢您！
